### PR TITLE
JSON - Added Overpass API JSON format + a number of bug fixes

### PR DESCRIPTION
**Pull request by mmd-osm**

### CODE REVIEW

**Comment by tomhughes** [comment]
This is just a fork - pull requests should go to upstream.

**Comment by mmd-osm** [comment]
Hmm did you read my comment in the other pull request?

Once you merge this pull request into your branch, it should automatically show up in this pull request here. I didn't want to create yet another pull request for the JSON topic in this repo. Let's see if this works out somehow.

**Comment by tomhughes** [comment]
I did, though only after I had closed this.

To be honest I though you had already merged my branch until I read that comment.

I'm certainly happy to take the compression fix, but the additional format is much more involved and is really dependent on what decision is made on what format to support - supporting multiple JSON formats has never been on the radar to my knowledge so I'm reluctant to get a simple fix mixed up with a potentially tricky issue like that.

**Comment by mmd-osm** [comment]
> supporting multiple JSON formats has never been on the radar

I simply changed to current implementation to produce the Overpass API JSON instead of the current format. The decision to switch to this format is still pending, but that's not a real issue. Once everyone agrees with it, we already have the code for it. If we don't want to go that route, we can still cherry-pick the compression fix.

**Comment by mmd-osm** [comment]
As there was no major objection to using the Overpass JSON format so far, I added more test cases for the /map call and improved some error messages. Please feel free to add further unit tests as needed. Once you think we've got enough feedback, please feel free to merge this one, so that @zerebubuth could maybe take a brief look at the final result before merging into master.

**Comment by mmd-osm** [comment]
In the meantime, I have created a dedicated branch json on the zerebubuth repository, which can be used to stage changes before merging into master. It already includes all of your and my changes: https://github.com/zerebubuth/openstreetmap-cgimap/tree/json

That's why I'm closing this pull request again...

**Pull request closed without merging**
